'''
    ezFBfont_spleen_12x24_t : generated as part of the microPyEZfonts repository
      https://github.com/easytarget/microPyEZfonts

    This font definition can be used with the "ezFBfont" class provided there.
    It can also be used with the "writer" class from Peter Hinches micropython
      font-to-py tool: https://github.com/peterhinch/micropython-font-to-py

    Original spleen-12x24.bdf font file was sourced from the U8G2 project:
      https://github.com/olikraus/u8g2

    Original Copyright information from source:
    COPYRIGHT "Copyright (c) 2018-2022, Frederic Cambus"

    Original Comments and Notices from source:
    (may include copyright and trademark info):
    COMMENT /*
    COMMENT  * Spleen 12x24 1.9.1
    COMMENT  * Copyright (c) 2018-2022, Frederic Cambus
    COMMENT  * https://www.cambus.net/
    COMMENT  *
    COMMENT  * Created:      2018-08-15
    COMMENT  * Last Updated: 2020-10-10
    COMMENT  *
    COMMENT  * Spleen is released under the BSD 2-Clause license.
    COMMENT  * See LICENSE file for details.
    COMMENT  *
    COMMENT  * SPDX-License-Identifier: BSD-2-Clause
    COMMENT  */
'''
# Code generated by bdf2dict.py
# Font: spleen-12x24 Char set: b' +-.0123456789:'
# Cmd: ['bdf2dict.py', 'bdf-sources/spleen-12x24.bdf', '../latin-1/t-char.set']
# Date: 2024-06-04 14:21:24

version = '0.33'
name = '-misc-spleen-medium-r-normal--24-240-72-72-C-120-ISO10646-1'
family = 'Spleen'
weight = 'Medium'
size = 24

def height():
    return 15

def baseline():
    return 15

def max_width():
    return 12

def hmap():
    return True

def reverse():
    return False

def monospaced():
    return True

def min_ch():
    return 32

def max_ch():
    return 58

_g = {
 32:[b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'],
 43:[b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x06\x00\x06\x00\x06\x00?\xc0\x06\x00\x06\x00\x06\x00\x00\x00\x00\x00\x00\x00'],
 45:[b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00?\xc0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'],
 46:[b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x06\x00\x06\x00'],
 48:[b'\x1f\x800\xc0`````\xe0a\xe0c`f`l`x`p`````0\xc0\x1f\x80'],
 49:[b'\x0e\x00\x1e\x006\x00&\x00\x06\x00\x06\x00\x06\x00\x06\x00\x06\x00\x06\x00\x06\x00\x06\x00\x06\x00\x06\x00?\xc0'],
 50:[b'\x1f\x800\xc0``\x00`\x00`\x00`\x00\xc0\x01\x80\x03\x00\x06\x00\x0c\x00\x18\x000\x00``\x7f\xe0'],
 51:[b'\x1f\x800\xc0``\x00`\x00`\x00\xc0\x0f\x80\x00\xc0\x00`\x00`\x00`\x00```0\xc0\x1f\x80'],
 52:[b'`\x00`\x00`\x00a\x80a\x80a\x80a\x80a\x80a\x80a\x80\x7f\xe0\x01\x80\x01\x80\x01\x80\x01\x80'],
 53:[b'\x7f\xe0```\x00`\x00`\x00`\x00\x7f\x80\x00\xc0\x00`\x00`\x00`\x00```0\xc0\x1f\x80'],
 54:[b'\x1f\xc00``\x00`\x00`\x00`\x00\x7f\x80`\xc0``````````0\xc0\x1f\x80'],
 55:[b'\x7f\xe0``\x00`\x00`\x00`\x00\xc0\x01\x80\x03\x00\x06\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00\x0c\x00'],
 56:[b'\x1f\x800\xc0``````0\xc0\x1f\x800\xc0``````````0\xc0\x1f\x80'],
 57:[b'\x1f\x800\xc0``````````0`\x1f\xe0\x00`\x00`\x00`\x00``\xc0?\x80'],
 58:[b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x06\x00\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x06\x00\x06\x00'],
}

def get_ch(ch):
    c = ord(ch)
    if c not in _g.keys():
        return None, 0, 0
    return memoryview(_g[c][0]), height(), max_width()

