'''
    ezFBfont_32_7_Seg_33x19_base : generated as part of the microPyEZfonts repository
      https://github.com/easytarget/microPyEZfonts

    This font definition can be used with the "ezFBfont" class provided there.
    It can also be used with the "writer" class from Peter Hinches micropython
      font-to-py tool: https://github.com/peterhinch/micropython-font-to-py

    Original 7_Seg_33x19.bdf font file was sourced from the U8G2 project:
      https://github.com/olikraus/u8g2

    Original Copyright information from source:
    COPYRIGHT "Created with Fony 1.4.0.2"

    Original Comments and Notices from source:
    (may include copyright and trademark info):
    COMMENT Exported by Fony v1.4.0.2
'''
# Code generated by bdf2dict.py
# Font: 7_Seg_33x19
# Cmd: [bdf2dict.py], ['Symbols-bdf-sources/7_Seg_33x19.bdf', './base-char.set', 'True']
# Date: 2024-06-11 17:20:47

version = '0.33'
name = '7_Seg_33x19'
family = 'None'
weight = 'None'
size = None

def height():
    return 32

def baseline():
    return 1

def max_width():
    return 19

def hmap():
    return True

def reverse():
    return False

def monospaced():
    return False

def min_ch():
    return 43

def max_ch():
    return 58

_g = {
 43:[b'',b'13'],
 44:[b'',b'7'],
 45:[b'',b'13'],
 46:[b'',b'7'],
 48:[b'',b'19'],
 49:[b'',b'19'],
 50:[b'',b'19'],
 51:[b'',b'19'],
 52:[b'',b'19'],
 53:[b'',b'19'],
 54:[b'',b'19'],
 55:[b'',b'19'],
 56:[b'',b'19'],
 57:[b'',b'19'],
 58:[b'',b'7'],
}

def get_ch(ch):
    c = ord(ch)
    if c not in _g.keys():
        return None, 0, 0
    return memoryview(_g[c][0]), 32, int(_g[c][1])

