'''
    ezFBfont_b14_t : generated as part of the microPyEZfonts repository
      https://github.com/easytarget/microPyEZfonts

    This font definition can be used with the "ezFBfont" class provided there.
    It can also be used with the "writer" class from Peter Hinches micropython
      font-to-py tool: https://github.com/peterhinch/micropython-font-to-py

    Original b14.bdf font file was sourced from the U8G2 project:
      https://github.com/olikraus/u8g2

    Original Copyright information from source:
    COPYRIGHT "(c) Copyright 2000-2003 /efont/ The Electronic Font Open Laboratory."

    Original Comments and Notices from source:
    (may include copyright and trademark info):
    None found
'''
# Code generated by bdf2dict.py
# Font: b14 Char set: b' +-.0123456789:'
# Cmd: ['bdf2dict.py', 'bdf-sources/b14.bdf', '../latin-1/t-char.set']
# Date: 2024-06-04 14:20:17

version = '0.33'
name = '-Efont-Biwidth-Medium-R-Normal--14-140-75-75-P-70-ISO10646-1'
family = 'Biwidth'
weight = 'Medium'
size = 14

def height():
    return 9

def baseline():
    return 9

def max_width():
    return 7

def hmap():
    return True

def reverse():
    return False

def monospaced():
    return True

def min_ch():
    return 32

def max_ch():
    return 58

_g = {
 32:[b'\x00\x00\x00\x00\x00\x00\x00\x00\x00'],
 43:[b'\x00\x10\x10\x10|\x10\x10\x10\x00'],
 45:[b'\x00\x00\x00\x00|\x00\x00\x00\x00'],
 46:[b'\x00\x00\x00\x00\x00\x00\x00\x18\x18'],
 48:[b'\x18$BBBBB$\x18'],
 49:[b'\x100P\x10\x10\x10\x10\x10|'],
 50:[b'<BB\x02\x0c\x10 @~'],
 51:[b'<BB\x02\x1c\x02BB<'],
 52:[b'\x04\x0c\x14\x14$D~\x04\x04'],
 53:[b'~@@|\x02\x02\x02B<'],
 54:[b'<B@@|BBB<'],
 55:[b'~\x02\x04\x04\x08\x08\x10\x10\x10'],
 56:[b'<BBB<BBB<'],
 57:[b'<BBB>\x02BB<'],
 58:[b'\x00\x00\x18\x18\x00\x00\x00\x18\x18'],
}

def get_ch(ch):
    c = ord(ch)
    if c not in _g.keys():
        return None, 0, 0
    return memoryview(_g[c][0]), height(), max_width()

