'''
    ezFBfont_b14_b_t : generated as part of the microPyEZfonts repository
      https://github.com/easytarget/microPyEZfonts

    This font definition can be used with the "ezFBfont" class provided there.
    It can also be used with the "writer" class from Peter Hinches micropython
      font-to-py tool: https://github.com/peterhinch/micropython-font-to-py

    Original b14_b.bdf font file was sourced from the U8G2 project:
      https://github.com/olikraus/u8g2

    Original Copyright information from source:
    COPYRIGHT "(c) Copyright 2000-2003 /efont/ The Electronic Font Open Laboratory."

    Original Comments and Notices from source:
    (may include copyright and trademark info):
    None found
'''
# Code generated by bdf2dict.py
# Font: b14_b Char set: b' +-.0123456789:'
# Cmd: ['bdf2dict.py', 'bdf-sources/b14_b.bdf', '../latin-1/t-char.set']
# Date: 2024-06-04 14:20:25

version = '0.33'
name = '-Efont-Biwidth-Bold-R-Normal--14-140-75-75-P-70-ISO10646-1'
family = 'Biwidth'
weight = 'Bold'
size = 14

def height():
    return 9

def baseline():
    return 9

def max_width():
    return 7

def hmap():
    return True

def reverse():
    return False

def monospaced():
    return True

def min_ch():
    return 32

def max_ch():
    return 58

_g = {
 32:[b'\x00\x00\x00\x00\x00\x00\x00\x00\x00'],
 43:[b'\x00000\xfc000\x00'],
 45:[b'\x00\x00\x00\x00\xfc\x00\x00\x00\x00'],
 46:[b'\x00\x00\x00\x00\x00\x00\x0088'],
 48:[b'8l\xc6\xc6\xc6\xc6\xc6l8'],
 49:[b'0p\xd000000\xfc'],
 50:[b'|\xc6\xc6\x06\x1c0`\xc0\xfe'],
 51:[b'|\xc6\xc6\x06<\x06\xc6\xc6|'],
 52:[b'\x0c\x1c44l\xcc\xfe\x0c\x0c'],
 53:[b'\xfe\xc0\xc0\xfc\x06\x06\x06\xc6|'],
 54:[b'|\xc6\xc0\xc0\xfc\xc6\xc6\xc6|'],
 55:[b'\xfe\x06\x0c\x0c\x18\x18000'],
 56:[b'|\xc6\xc6\xc6|\xc6\xc6\xc6|'],
 57:[b'|\xc6\xc6\xc6~\x06\xc6\xc6|'],
 58:[b'\x00\x0088\x00\x00\x0088'],
}

def get_ch(ch):
    c = ord(ch)
    if c not in _g.keys():
        return None, 0, 0
    return memoryview(_g[c][0]), height(), max_width()

