'''
    ezFBfont_open_iconic_weather_1x_0x40_0x79_08 : generated as part of the microPyEZfonts repository
      https://github.com/easytarget/microPyEZfonts

    This font definition can be used with the "ezFBfont" class provided there.
    It can also be used with the "writer" class from Peter Hinches micropython
      font-to-py tool: https://github.com/peterhinch/micropython-font-to-py

    Original open_iconic_weather_1x.bdf font file was sourced from the U8G2 project:
      https://github.com/olikraus/u8g2

'''
# Code generated by bdf2dict.py
# Font: open_iconic_weather_1x
# Cmd: ['bdf2dict.py'], ['Symbols-bdf-sources/open_iconic_weather_1x.bdf', '_', './0x40_0x79-char.set']
# Date: 2024-07-31 15:36:44
'''
    Original Copyright, Comments and Notices from source:

    COMMENT "https://github.com/iconic/open-iconic, SIL OPEN FONT LICENSE"
'''
version = '0.33'
name = 'open_iconic_weather_1x'
family = 'iconic'
weight = 'none'
size = None

def height():
    return 8

def baseline():
    return 8

def max_width():
    return 8

def hmap():
    return True

def reverse():
    return False

def monospaced():
    return True

def min_ch():
    return 64

def max_ch():
    return 69

_g = {
  64:b'\x00\x1c>~\xff\xff\x7f\x00',
  65:b'p\xe0\xdc>~\xff\xff\x7f',
  66:b'\x00`\xe0\xe0\xf0\xfe~\x18',
  67:b'\x1c>~\xff\xc7\x11TT',
  68:b'\x00\x00\x18~<<$\x00',
  69:b'\x00B\x18<<\x18B\x00',
}

def get_ch(ch):
    c = ord(ch)
    if c not in _g.keys():
        return None, 0, 0
    return memoryview(_g[c]), 8, 8
