'''
    ezFBfont_cursorr_t : generated as part of the microPyEZfonts repository
      https://github.com/easytarget/microPyEZfonts

    This font definition can be used with the "ezFBfont" class provided there.
    It can also be used with the "writer" class from Peter Hinches micropython
      font-to-py tool: https://github.com/peterhinch/micropython-font-to-py

    Original cursorr.bdf font file was sourced from the U8G2 project:
      https://github.com/olikraus/u8g2

    Original Copyright information from source:
    COPYRIGHT "These "glyphs" are unencumbered"

    Original Comments and Notices from source:
    (may include copyright and trademark info):
    None found
'''
# Code generated by bdf2dict.py
# Font: cursorr Char set: b' +-.0123456789:'
# Cmd: ['bdf2dict.py', 'bdf-sources/cursorr.bdf', '../latin-1/t-char.set']
# Date: 2024-06-04 14:20:55

version = '0.33'
name = 'cursor'
family = 'None'
weight = 'None'
size = None

def height():
    return 17

def baseline():
    return 1

def max_width():
    return 17

def hmap():
    return True

def reverse():
    return False

def monospaced():
    return True

def min_ch():
    return 45

def max_ch():
    return 46

_g = {
 45:[b'\x00\x00\x00\x00\x03\x00\x00\x0f\x00\x00?\x00\x00\xfe\x00\x03\xfc\x00\x0f\xfc\x00?\xf8\x00?\xf8\x00\x03\xf0\x00\x07\xf0\x00\x0e\xe0\x00\x1c\xe0\x008\xc0\x00p\xc0\x00`\x00\x00@\x00\x00'],
 46:[b'\x00\x00\x00\x00\x01\x00\x00\x06\x00\x00\x1e\x00\x00|\x00\x01\xfc\x00\x008\x00\x00X\x00\x00\x90\x00\x01\x10\x00\x02\x00\x00\x04\x00\x00\x08\x00\x00\x10\x00\x00 \x00\x00@\x00\x00\x00\x00\x00'],
}

def get_ch(ch):
    c = ord(ch)
    if c not in _g.keys():
        return None, 0, 0
    return memoryview(_g[c][0]), height(), max_width()

