'''
    mPyEZfont_u8g2_4x6_n.py : generated as part of the microPyEZfonts repository
      https://github.com/easytarget/microPyEZfonts

    Original 4x6.bdf font file was sourced from the U8G2 project:
      https://github.com/olikraus/u8g2

    This font definition can be used with the "writer" class from Peter Hinches
      micropython font-to-py tool, and was generated using his tooling from
      https://github.com/peterhinch/micropython-font-to-py

    Original Copyright Notice from source:

    COPYRIGHT "Public domain font.  Share and enjoy."

    Original Comments from source (may include copyright info):

    None found:
'''

# Code generated by font_to_py.py.
# Font: 4x6.bdf Char set:  *+,-./0123456789:
# Cmd: micropython-font-to-py/font_to_py.py -x -k mpy-fonts/n-char.set u8g2/tools/font/bdf/4x6.bdf 0 tmp_mPyEZfont_u8g2_4x6_n.py
version = '0.33'

def height():
    return 6

def baseline():
    return 5

def max_width():
    return 4

def hmap():
    return True

def reverse():
    return False

def monospaced():
    return False

def min_ch():
    return 32

def max_ch():
    return 63

_font =\
b'\x04\x00\xc0\x20\x40\x00\x40\x00\x04\x00\x00\x00\x00\x00\x00\x00'\
b'\x04\x00\xa0\x40\xe0\x40\xa0\x00\x04\x00\x40\x40\xe0\x40\x40\x00'\
b'\x04\x00\x00\x00\x00\x00\x40\x80\x04\x00\x00\x00\xe0\x00\x00\x00'\
b'\x04\x00\x00\x00\x00\x00\x40\x00\x04\x00\x20\x20\x40\x80\x80\x00'\
b'\x04\x00\x40\xa0\xe0\xa0\x40\x00\x04\x00\x40\xc0\x40\x40\xe0\x00'\
b'\x04\x00\x40\xa0\x20\x40\xe0\x00\x04\x00\xe0\x20\x40\x20\xc0\x00'\
b'\x04\x00\xa0\xa0\xe0\x20\x20\x00\x04\x00\xe0\x80\xc0\x20\xc0\x00'\
b'\x04\x00\x60\x80\xc0\xa0\x40\x00\x04\x00\xe0\x20\x40\x80\x80\x00'\
b'\x04\x00\x60\xa0\x40\xa0\xc0\x00\x04\x00\x40\xa0\x60\x20\xc0\x00'\
b'\x04\x00\x00\x40\x00\x00\x40\x00'

_index =\
b'\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'\
b'\x00\x00\x00\x00\x00\x00\x10\x00\x18\x00\x20\x00\x28\x00\x30\x00'\
b'\x38\x00\x40\x00\x48\x00\x50\x00\x58\x00\x60\x00\x68\x00\x70\x00'\
b'\x78\x00\x80\x00\x88\x00\x90\x00\x00\x00\x00\x00\x00\x00\x00\x00'\
b'\x00\x00\x98\x00'

_mvfont = memoryview(_font)
_mvi = memoryview(_index)
ifb = lambda l : l[0] | (l[1] << 8)

def get_ch(ch):
    oc = ord(ch)
    ioff = 2 * (oc - 32 + 1) if oc >= 32 and oc <= 63 else 0
    doff = ifb(_mvi[ioff : ])
    width = ifb(_mvfont[doff : ])

    next_offs = doff + 2 + ((width - 1)//8 + 1) * 6
    return _mvfont[doff + 2:next_offs], 6, width
 
