'''
    ezFBfont_16_open_iconic_check_2x_lower : generated as part of the microPyEZfonts repository
      https://github.com/easytarget/microPyEZfonts

    This font definition can be used with the "ezFBfont" class provided there.
    It can also be used with the "writer" class from Peter Hinches micropython
      font-to-py tool: https://github.com/peterhinch/micropython-font-to-py

    Original open_iconic_check_2x.bdf font file was sourced from the U8G2 project:
      https://github.com/olikraus/u8g2

    Original Copyright information from source:
    COPYRIGHT "https://github.com/iconic/open-iconic, SIL OPEN FONT LICENSE"

    Original Comments and Notices from source:
    (may include copyright and trademark info):
    None found
'''
# Code generated by bdf2dict.py
# Font: open_iconic_check_2x
# Cmd: [bdf2dict.py], ['Symbols-bdf-sources/open_iconic_check_2x.bdf', '_', './lower-char.set']
# Date: 2024-06-13 11:38:25

version = '0.33'
name = '"open_iconic_check_2x"'
family = 'None'
weight = 'None'
size = None

def height():
    return 16

def baseline():
    return 16

def max_width():
    return 16

def hmap():
    return True

def reverse():
    return False

def monospaced():
    return True

def min_ch():
    return 64

def max_ch():
    return 68

_g = {
 64:[b'\x00\x00\x00\x00\x00\x08\x00\x1c\x00>\x00~ \xfcq\xf8\xfb\xf0\x7f\xe0?\xc0\x1f\x80\x0f\x00\x06\x00\x00\x00\x00\x00'],
 65:[b'\x07\xe0\x1f\xf8?\xfc\x7f\xfe\x7f\xe6\xff\xc7\xff\x8f\xf3\x1f\xf0?\xf8\x7f\xfc\xff\x7f\xfe\x7f\xfe?\xfc\x1f\xf8\x07\xe0'],
 66:[b'\x07\xe0\x1f\xf8?\xfc\x7f\xfes\xce\xf1\x8f\xf8\x1f\xfc?\xfc?\xf8\x1f\xf1\x8fs\xce\x7f\xfe?\xfc\x1f\xf8\x07\xe0'],
 67:[b'\xff\xe0\xff\xc6\xc0\x0e\xc0\x1c\xc08\xc6p\xc7\xe0\xc3\xc4\xc1\x8c\xc0\x0c\xc0\x0c\xc0\x0c\xff\xfc\xff\xfc\x00\x00\x00\x00'],
 68:[b' \x08p\x1c\xf8>|~>\xfc\x1f\xf8\x0f\xf0\x07\xe0\x0f\xe0\x1f\xf0?\xf8~|\xfc>x\x1e0\x0c\x00\x00'],
}

def get_ch(ch):
    c = ord(ch)
    if c not in _g.keys():
        return None, 0, 0
    return memoryview(_g[c][0]), 16, 16

