'''
    ezFBfont_08_open_iconic_app_1x_lower : generated as part of the microPyEZfonts repository
      https://github.com/easytarget/microPyEZfonts

    This font definition can be used with the "ezFBfont" class provided there.
    It can also be used with the "writer" class from Peter Hinches micropython
      font-to-py tool: https://github.com/peterhinch/micropython-font-to-py

    Original open_iconic_app_1x.bdf font file was sourced from the U8G2 project:
      https://github.com/olikraus/u8g2

    Original Copyright information from source:
    COPYRIGHT "https://github.com/iconic/open-iconic, SIL OPEN FONT LICENSE"

    Original Comments and Notices from source:
    (may include copyright and trademark info):
    None found
'''
# Code generated by bdf2dict.py
# Font: open_iconic_app_1x
# Cmd: [bdf2dict.py], ['Symbols-bdf-sources/open_iconic_app_1x.bdf', '_', './lower-char.set']
# Date: 2024-06-13 11:38:18

version = '0.33'
name = '"open_iconic_app_1x"'
family = 'None'
weight = 'None'
size = None

def height():
    return 8

def baseline():
    return 8

def max_width():
    return 8

def hmap():
    return True

def reverse():
    return False

def monospaced():
    return True

def min_ch():
    return 64

def max_ch():
    return 72

_g = {
 64:[b'\x1c\\\xe3\xc3\x03@n,'],
 65:[b'\xfe\x82\x82\xfe\xaa\xfa\xaa\xfe'],
 66:[b'\xfe\xfe\x00\xfe\xaa\xfe\xae\xfe'],
 67:[b'\x0c\x1e\xff\xb3\xed\xed\xf3\xff'],
 68:[b'\xf8\xc0\xdf\xdf\x1f\x1f\x00\x00'],
 69:[b'<B\x81\x81\x89\x81B<'],
 70:[b'<B\x85\x99\x99\xa1B<'],
 71:[b'\x18\xef\x8f\x8fNN,\x18'],
 72:[b'88@\x8a\x92\x82D8'],
}

def get_ch(ch):
    c = ord(ch)
    if c not in _g.keys():
        return None, 0, 0
    return memoryview(_g[c][0]), 8, 8

