'''
    ezFBfont_b12_b_t : generated as part of the microPyEZfonts repository
      https://github.com/easytarget/microPyEZfonts

    This font definition can be used with the "ezFBfont" class provided there.
    It can also be used with the "writer" class from Peter Hinches micropython
      font-to-py tool: https://github.com/peterhinch/micropython-font-to-py

    Original b12_b.bdf font file was sourced from the U8G2 project:
      https://github.com/olikraus/u8g2

    Original Copyright information from source:
    COPYRIGHT "(c) Copyright 2000-2003 /efont/ The Electronic Font Open Laboratory."

    Original Comments and Notices from source:
    (may include copyright and trademark info):
    None found
'''
# Code generated by bdf2dict.py
# Font: b12_b Char set: b' +-.0123456789:'
# Cmd: ['bdf2dict.py', 'bdf-sources/b12_b.bdf', '../latin-1/t-char.set']
# Date: 2024-06-04 14:20:11

version = '0.33'
name = '-Efont-Biwidth-Bold-R-Normal--12-120-75-75-P-60-ISO10646-1'
family = 'Biwidth'
weight = 'Bold'
size = 12

def height():
    return 7

def baseline():
    return 7

def max_width():
    return 6

def hmap():
    return True

def reverse():
    return False

def monospaced():
    return True

def min_ch():
    return 32

def max_ch():
    return 58

_g = {
 32:[b'\x00\x00\x00\x00\x00\x00\x00'],
 43:[b'\x0000\xfc00\x00'],
 45:[b'\x00\x00\x00\xfc\x00\x00\x00'],
 46:[b'\x00\x00\x00\x00\x00pp'],
 48:[b'8lllll8'],
 49:[b'0p0000x'],
 50:[b'x\xcc\x0c\x180`\xfc'],
 51:[b'\xfc\x0c\x188\x0c\xccx'],
 52:[b'\x188h\xd8\xfc\x18\x18'],
 53:[b'\xfc\xc0\xf8\x0c\x0c\xccx'],
 54:[b'8`\xc0\xf8\xcc\xccx'],
 55:[b'\xfc\x0c\x18\x18000'],
 56:[b'x\xcc\xccx\xcc\xccx'],
 57:[b'x\xcc\xcc|\x0c\x18p'],
 58:[b'\x00\x00pp\x00pp'],
}

def get_ch(ch):
    c = ord(ch)
    if c not in _g.keys():
        return None, 0, 0
    return memoryview(_g[c][0]), height(), max_width()

