'''
    ezFBfont_open_iconic_mime_1x_e : generated as part of the microPyEZfonts repository
      https://github.com/easytarget/microPyEZfonts

    This font definition can be used with the "ezFBfont" class provided there.
    It can also be used with the "writer" class from Peter Hinches micropython
      font-to-py tool: https://github.com/peterhinch/micropython-font-to-py

    Original open_iconic_mime_1x.bdf font file was sourced from the U8G2 project:
      https://github.com/olikraus/u8g2

    Original Copyright information from source:
    COPYRIGHT "https://github.com/iconic/open-iconic, SIL OPEN FONT LICENSE"

    Original Comments and Notices from source:
    (may include copyright and trademark info):
    None found
'''
# Code generated by bdf2dict.py
# Font: open_iconic_mime_1x Char set: b' !"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~\xa0\xa1\xa2\xa3\xa4\xa5\xa6\xa7\xa8\xa9\xaa\xab\xac\xad\xae\xaf\xb0\xb1\xb2\xb3\xb4\xb5\xb6\xb7\xb8\xb9\xba\xbb\xbc\xbd\xbe\xbf\xc0\xc1\xc2\xc3\xc4\xc5\xc6\xc7\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\xd0\xd1\xd2\xd3\xd4\xd5\xd6\xd7\xd8\xd9\xda\xdb\xdc\xdd\xde\xdf\xe0\xe1\xe2\xe3\xe4\xe5\xe6\xe7\xe8\xe9\xea\xeb\xec\xed\xee\xef\xf0\xf1\xf2\xf3\xf4\xf5\xf6\xf7\xf8\xf9\xfa\xfb\xfc\xfd\xfe\xff'
# Cmd: ['bdf2dict.py', 'bdf-sources/open_iconic_mime_1x.bdf', '../latin-1/e-char.set']
# Date: 2024-06-04 14:21:17

version = '0.33'
name = '"open_iconic_mime_1x"'
family = 'None'
weight = 'None'
size = None

def height():
    return 8

def baseline():
    return 8

def max_width():
    return 8

def hmap():
    return True

def reverse():
    return False

def monospaced():
    return True

def min_ch():
    return 64

def max_ch():
    return 77

_g = {
 64:[b'\x00B\x81\xa5\xa5\xc3\x00\x00'],
 65:[b'\xf2\xf2\xf2\xfe\xfe\xfe\x80\xfe'],
 66:[b'\xe0\xe8\xac\xe0\xbe\xfe\x86\xfe'],
 67:[b'\xe0\xff\x00\xff\xff\xff\xff\xff'],
 68:[b'\xff\x81\x81\x81\xe3\xf1\xf9\xff'],
 69:[b'\x81\xb1\x81\x99\x81\x8d\x81\x00'],
 70:[b'\xff\xa1\xff\xa1\xff\xa1\xff\x00'],
 71:[b'\x00\xfc\xfd\xff\xfd\xfc\x00\x00'],
 72:[b'\x10\xba\x82\xfe\xfe\xfe\xfe\xfe'],
 73:[b'\xe0\xe8\xec\xe0\xfe\xfe\xfe\xfe'],
 74:[b'\x00\x02\x048@\x80\x00\xff'],
 75:[b'04\x16\xc7\xe7\xcf\x1e\x1c'],
 76:[b'?// >\xbe\xbe\xfe'],
 77:[b'8\xfe\x00TTTT|'],
}

def get_ch(ch):
    c = ord(ch)
    if c not in _g.keys():
        return None, 0, 0
    return memoryview(_g[c][0]), height(), max_width()

