'''
    ezFBfont_open_iconic_play_1x_u : generated as part of the microPyEZfonts repository
      https://github.com/easytarget/microPyEZfonts

    This font definition can be used with the "ezFBfont" class provided there.
    It can also be used with the "writer" class from Peter Hinches micropython
      font-to-py tool: https://github.com/peterhinch/micropython-font-to-py

    Original open_iconic_play_1x.bdf font file was sourced from the U8G2 project:
      https://github.com/olikraus/u8g2

    Original Copyright information from source:
    COPYRIGHT "https://github.com/iconic/open-iconic, SIL OPEN FONT LICENSE"

    Original Comments and Notices from source:
    (may include copyright and trademark info):
    None found
'''
# Code generated by bdf2dict.py
# Font: open_iconic_play_1x Char set: b' !"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_'
# Cmd: ['bdf2dict.py', 'bdf-sources/open_iconic_play_1x.bdf', '../latin-1/u-char.set']
# Date: 2024-06-04 14:21:19

version = '0.33'
name = '"open_iconic_play_1x"'
family = 'None'
weight = 'None'
size = None

def height():
    return 8

def baseline():
    return 8

def max_width():
    return 8

def hmap():
    return True

def reverse():
    return False

def monospaced():
    return True

def min_ch():
    return 64

def max_ch():
    return 81

_g = {
 64:[b'\x08(*\xaa\xaa*(\x08'],
 65:[b'\x02\x1a\xfa\xfaz" \x00'],
 66:[b'\x00\x18<~\xff\x00\xff\xff'],
 67:[b'<fBB\xc3\xc3\xc3\x00'],
 68:[b'\x00ffffff\x00'],
 69:[b'\x00@p||p@\x00'],
 70:[b'\x00<~~~~<\x00'],
 71:[b'\x00\x113ww3\x11\x00'],
 72:[b'\x00\x88\xcc\xee\xee\xcc\x88\x00'],
 73:[b'\x00\xc2\xc6\xde\xde\xc6\xc2\x00'],
 74:[b'\x00\x86\xc6\xf6\xf6\xc6\x86\x00'],
 75:[b'\x00~~~~~~\x00'],
 76:[b'\x18\x18ZZf<\x08<'],
 77:[b"\x1f?!!'\xe7\xe7\xe0"],
 78:[b'<~\xef\xe7\xe7\xef~<'],
 79:[b'\x106\xf3\xf5\xf5\xf36\x10'],
 80:[b'\x08\x18xzzx\x18\x08'],
 81:[b'\x04\x0c<<<<\x0c\x04'],
}

def get_ch(ch):
    c = ord(ch)
    if c not in _g.keys():
        return None, 0, 0
    return memoryview(_g[c][0]), height(), max_width()

