'''
    ezFBfont_18_ncenR18_time : generated as part of the microPyEZfonts repository
      https://github.com/easytarget/microPyEZfonts

    This font definition can be used with the "ezFBfont" class provided there.
    It can also be used with the "writer" class from Peter Hinches micropython
      font-to-py tool: https://github.com/peterhinch/micropython-font-to-py

    Original ncenR18.bdf font file was sourced from the U8G2 project:
      https://github.com/olikraus/u8g2

'''
# Code generated by bdf2dict.py
# Font: ncenR18
# Cmd: ['bdf2dict.py'], ['Latin-1-bdf-sources/ncenR18.bdf', '_', './time-char.set']
# Date: 2024-06-18 20:27:37
'''
    Original Copyright, Comments and Notices from source:

    COPYRIGHT ISO10646-1 extension by Markus Kuhn <mkuhn@acm.org>, 2001-03-20
    COPYRIGHT 
    COPYRIGHT +
    COPYRIGHT Copyright 1984-1989, 1994 Adobe Systems Incorporated.
    COPYRIGHT Copyright 1988, 1994 Digital Equipment Corporation.
    COPYRIGHT 
    COPYRIGHT Adobe is a trademark of Adobe Systems Incorporated which may be
    COPYRIGHT registered in certain jurisdictions.
    COPYRIGHT Permission to use these trademarks is hereby granted only in
    COPYRIGHT association with the images described in this file.
    COPYRIGHT 
    COPYRIGHT Permission to use, copy, modify, distribute and sell this software
    COPYRIGHT and its documentation for any purpose and without fee is hereby
    COPYRIGHT granted, provided that the above copyright notices appear in all
    COPYRIGHT copies and that both those copyright notices and this permission
    COPYRIGHT notice appear in supporting documentation, and that the names of
    COPYRIGHT Adobe Systems and Digital Equipment Corporation not be used in
    COPYRIGHT advertising or publicity pertaining to distribution of the software
    COPYRIGHT without specific, written prior permission.  Adobe Systems and
    COPYRIGHT Digital Equipment Corporation make no representations about the
    COPYRIGHT suitability of this software for any purpose.  It is provided "as
    COPYRIGHT is" without express or implied warranty.
    COPYRIGHT -

    COMMENT "Copyright (c) 1984, 1987 Adobe Systems Incorporated. All Rights Reserved. Copyright (c) 1988, 1991 Digital Equipment Corporation. All Rights Reserved."

    NOTICE "New Century Schoolbook is a trademark of Linotype-Hell AG and/or its subsidiaries."
'''
version = '0.33'
name = '-adobe-new century schoolbook-medium-r-normal--25-180-100-100-p-136-iso10646-1'
family = 'new century schoolbook'
weight = 'medium'
size = 25

def height():
    return 18

def baseline():
    return 18

def max_width():
    return 14

def hmap():
    return True

def reverse():
    return False

def monospaced():
    return False

def min_ch():
    return 32

def max_ch():
    return 58

_g = {
  32:b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x07',
  43:b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x03\x00\x03\x00\x03\x00\x03\x00\x7f\xf8\x7f\xf8\x03\x00\x03\x00\x03\x00\x03\x00\x03\x00\x00\x00\x0e',
  45:b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00~~\x00\x00\x00\x00\x00\x00\x08',
  46:b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00888\x07',
  48:b'\x07\x00\x08\x80\x18\xc0\x10@0`0`pppppppppppp0`0`\x10@\x18\xc0\x08\x80\x07\x00\r',
  49:b'\x01\x00\x07\x00\x1f\x00\x03\x00\x03\x00\x03\x00\x03\x00\x03\x00\x03\x00\x03\x00\x03\x00\x03\x00\x03\x00\x03\x00\x03\x00\x03\x00\x03\x00\x1f\xe0\r',
  50:b'\x0f\x808\xe0 `pppp p\x00`\x00\xe0\x00\xc0\x01\x80\x03\x00\x06\x00\x0c\x00\x18\x100\x10`0\x7f\xf0\x7f\xf0\r',
  51:b'\x0f\x801\xc0`\xe0p\xe0p\xe0 \xc0\x00\xc0\x01\x80\x0f\x80\x00\xc0\x00`\x00p pppp``\xe00\xc0\x0f\x00\r',
  52:b'\x00@\x00\xc0\x01\xc0\x03\xc0\x06\xc0\x0c\xc0\x08\xc0\x18\xc00\xc0`\xc0@\xc0\xc0\xc0\x80\xc0\xff\xf0\x00\xc0\x00\xc0\x00\xc0\x03\xf0\r',
  53:b'?\xe0?\xc0 \x00 \x00 \x00 \x00 \x00/\x801\xc0\x00`\x00`\x00p0pppp` `0\xc0\x0f\x80\r',
  54:b'\x07\xc0\x1cp\x10p000\x000\x00p\x00w\x80x\xc0p`p`pppp0p0`0`\x18\xc0\x0f\x80\r',
  55:b'?\xf0?\xf0   `\x00@\x00\xc0\x00\xc0\x00\x80\x01\x80\x01\x80\x01\x00\x03\x00\x03\x00\x03\x00\x07\x00\x07\x00\x07\x00\x02\x00\r',
  56:b'\x0f\x80\x18\xc0\x10@0`0`8`\x1c\xc0\x1f\x80\x0f\x80\x1b\xc00\xe0`p`0`0`00`8\xe0\x0f\x80\r',
  57:b'\x0f\x80\x18\xc08`0`pppppp0p8p\x18\xf0\x0fp\x00p\x00`\x00``\xe0p\xc0q\xc0\x1f\x00\r',
  58:b'\x00\x00\x00\x00\x00\x00888\x00\x00\x00\x00\x00\x00888\x07',
}

def get_ch(ch):
    c = ord(ch)
    if c not in _g.keys():
        return None, 0, 0
    return memoryview(_g[c]), 18, int(_g[c][-1])
