'''
    ezFBfont_06_4x6_num : generated as part of the microPyEZfonts repository
      https://github.com/easytarget/microPyEZfonts

    This font definition can be used with the "ezFBfont" class provided there.
    It can also be used with the "writer" class from Peter Hinches micropython
      font-to-py tool: https://github.com/peterhinch/micropython-font-to-py

    Original 4x6.bdf font file was sourced from the U8G2 project:
      https://github.com/olikraus/u8g2

    Original Copyright information from source:
    COPYRIGHT "Public domain font.  Share and enjoy."

    Original Comments and Notices from source:
    (may include copyright and trademark info):
    None found
'''
# Code generated by bdf2dict.py
# Font: 4x6
# Cmd: [bdf2dict.py], ['Latin-1-bdf-sources/4x6.bdf', './num-char.set', 'True']
# Date: 2024-06-11 17:32:28

version = '0.33'
name = '-Misc-Fixed-Medium-R-Normal--6-60-75-75-C-40-ISO10646-1'
family = 'fixed'
weight = 'medium'
size = 6

def height():
    return 6

def baseline():
    return 5

def max_width():
    return 4

def hmap():
    return True

def reverse():
    return False

def monospaced():
    return True

def min_ch():
    return 32

def max_ch():
    return 176

_g = {
 32:[b'\x00\x00\x00\x00\x00\x00'],
 37:[b'\x80 @\x80 \x00'],
 40:[b' @@@@ '],
 41:[b'\x80@@@@\x80'],
 42:[b'\xa0@\xe0@\xa0\x00'],
 43:[b'@@\xe0@@\x00'],
 44:[b'\x00\x00\x00\x00@\x80'],
 45:[b'\x00\x00\xe0\x00\x00\x00'],
 46:[b'\x00\x00\x00\x00@\x00'],
 47:[b'  @\x80\x80\x00'],
 48:[b'@\xa0\xe0\xa0@\x00'],
 49:[b'@\xc0@@\xe0\x00'],
 50:[b'@\xa0 @\xe0\x00'],
 51:[b'\xe0 @ \xc0\x00'],
 52:[b'\xa0\xa0\xe0  \x00'],
 53:[b'\xe0\x80\xc0 \xc0\x00'],
 54:[b'`\x80\xc0\xa0@\x00'],
 55:[b'\xe0 @\x80\x80\x00'],
 56:[b'`\xa0@\xa0\xc0\x00'],
 57:[b'@\xa0` \xc0\x00'],
 58:[b'\x00@\x00\x00@\x00'],
 176:[b'@\xa0@\x00\x00\x00'],
}

def get_ch(ch):
    c = ord(ch)
    if c not in _g.keys():
        return None, 0, 0
    return memoryview(_g[c][0]), 6, 4

