'''
    ezFBfont_08_amstrad_cpc_extended_upper : generated as part of the microPyEZfonts repository
      https://github.com/easytarget/microPyEZfonts

    This font definition can be used with the "ezFBfont" class provided there.
    It can also be used with the "writer" class from Peter Hinches micropython
      font-to-py tool: https://github.com/peterhinch/micropython-font-to-py

    Original amstrad_cpc_extended.bdf font file was sourced from the U8G2 project:
      https://github.com/olikraus/u8g2

    Original Copyright information from source:
    COPYRIGHT "Copyright ruboku 2008"

    Original Comments and Notices from source:
    (may include copyright and trademark info):
    COMMENT
    COMMENT Converted from OpenType font "Amstrad-CPC-extended.ttf" by "otf2bdf 3.0".
    COMMENT
'''
# Code generated by bdf2dict.py
# Font: amstrad_cpc_extended
# Cmd: [bdf2dict.py], ['Latin-1-bdf-sources/amstrad_cpc_extended.bdf', './upper-char.set', 'True']
# Date: 2024-06-11 17:33:38

version = '0.33'
name = '-FreeType-Amstrad CPC extended-Medium-R-Normal--8-80-72-72-P-64-ISO10646-1'
family = 'amstrad cpc extended'
weight = 'medium'
size = 8

def height():
    return 8

def baseline():
    return 8

def max_width():
    return 9

def hmap():
    return True

def reverse():
    return False

def monospaced():
    return False

def min_ch():
    return 32

def max_ch():
    return 95

_g = {
 32:[b'\x00\x00\x00\x00\x00\x00\x00\x00',b'6'],
 33:[b'00000\x000\x00',b'6'],
 34:[b'lll\x00\x00\x00\x00\x00',b'7'],
 35:[b'll\xfe|\xfell\x00',b'8'],
 36:[b'\x18>X<\x1a|\x18\x00',b'8'],
 37:[b'\x00\xc6\xcc\x180f\xc6\x00',b'8'],
 38:[b'8l8v\xdc\xccv\x00',b'8'],
 39:[b'000\x00\x00\x00\x00\x00',b'6'],
 40:[b'\x180```0\x18\x00',b'7'],
 41:[b'`0\x18\x18\x180`\x00',b'7'],
 42:[b'\x00\x00f\x00<\x00\xff\x00<\x00f\x00\x00\x00\x00\x00',b'9'],
 43:[b'\x00\x18\x18~\x18\x18\x00\x00',b'8'],
 44:[b'\x00\x00\x00\x00\x0000`',b'6'],
 45:[b'\x00\x00\x00~\x00\x00\x00\x00',b'8'],
 46:[b'\x00\x00\x00\x00\x0000\x00',b'6'],
 47:[b'\x06\x0c\x180`\xc0\x80\x00',b'8'],
 48:[b'|\xc6\xce\xd6\xe6\xc6|\x00',b'8'],
 49:[b'\x188\x18\x18\x18\x18~\x00',b'8'],
 50:[b'<f\x06<`f~\x00',b'8'],
 51:[b'<F\x06\x1c\x06f<\x00',b'8'],
 52:[b'\x188X\x98\xfe\x18<\x00',b'8'],
 53:[b'~b`<\x06f<\x00',b'8'],
 54:[b'<f`|ff<\x00',b'8'],
 55:[b'~F\x0e\x0c\x18\x18\x18\x00',b'8'],
 56:[b'<ff<ff<\x00',b'8'],
 57:[b'<ff>\x06f<\x00',b'8'],
 58:[b'\x00\x0000\x0000\x00',b'6'],
 59:[b'\x00\x0000\x0000`',b'6'],
 60:[b'\x0c\x180`0\x18\x0c\x00',b'7'],
 61:[b'\x00\x00~\x00\x00~\x00\x00',b'8'],
 62:[b'`0\x18\x0c\x180`\x00',b'7'],
 63:[b'<f\x06\x0c\x18\x00\x18\x00',b'8'],
 64:[b'|\xc6\xde\xde\xde\xc0|\x00',b'8'],
 65:[b'\x18<ff~ff\x00',b'8'],
 66:[b'\xfcff|ff\xfc\x00',b'8'],
 67:[b'<f\xc0\xc0\xc0f<\x00',b'8'],
 68:[b'\xf8lfffl\xf8\x00',b'8'],
 69:[b'\xfebhxhb\xfe\x00',b'8'],
 70:[b'\xfebhxh`\xf0\x00',b'8'],
 71:[b'<f\xc0\xc0\xce\xc6~\x00',b'8'],
 72:[b'fff~fff\x00',b'8'],
 73:[b'~\x18\x18\x18\x18\x18~\x00',b'8'],
 74:[b'\x1e\x0c\x0c\x0c\xcc\xccx\x00',b'8'],
 75:[b'\xe6flxlf\xe6\x00',b'8'],
 76:[b'\xf0```bf\xfe\x00',b'8'],
 77:[b'\xc6\xee\xfe\xfe\xd6\xc6\xc6\x00',b'8'],
 78:[b'\xc6\xe6\xf6\xde\xce\xc6\xc6\x00',b'8'],
 79:[b'8l\xc6\xc6\xc6l8\x00',b'8'],
 80:[b'\xfcffx``\xf0\x00',b'8'],
 81:[b'8l\xc6\xc6\xda\xccv\x00',b'8'],
 82:[b'\xfcff|lf\xe2\x00',b'8'],
 83:[b'<f`<\x06f<\x00',b'8'],
 84:[b'~Z\x18\x18\x18\x18<\x00',b'8'],
 85:[b'ffffff<\x00',b'8'],
 86:[b'fffff<\x18\x00',b'8'],
 87:[b'\xc6\xc6\xc6\xd6\xfe\xee\xc6\x00',b'8'],
 88:[b'\xc6l88l\xc6\xc6\x00',b'8'],
 89:[b'fff<\x18\x18<\x00',b'8'],
 90:[b'\xfe\xc6\x8c\x182f\xfe\x00',b'8'],
 91:[b'x`````x\x00',b'7'],
 92:[b'\xc0`0\x18\x0c\x06\x02\x00',b'8'],
 93:[b'x\x18\x18\x18\x18\x18x\x00',b'7'],
 94:[b'\x108l\xc6\x00\x00\x00\x00',b'8'],
 95:[b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\x00',b'9'],
}

def get_ch(ch):
    c = ord(ch)
    if c not in _g.keys():
        return None, 0, 0
    return memoryview(_g[c][0]), 8, int(_g[c][1])

