'''
    ezFBfont_PTSansNarrow_14_upper_20 : generated as part of the microPyEZfonts repository
      https://github.com/easytarget/microPyEZfonts

    This font definition can be used with the "ezFBfont" class provided there.
    It can also be used with the "writer" class from Peter Hinches micropython
      font-to-py tool: https://github.com/peterhinch/micropython-font-to-py

    Original PTSansNarrow_14.bdf font file was sourced from the U8G2 project:
      https://github.com/olikraus/u8g2

'''
# Code generated by bdf2dict.py
# Font: PTSansNarrow_14
# Cmd: ['bdf2dict.py'], ['./PTSansNarrow-14.bdf', '_', './upper-char.set']
# Date: 2025-05-29 13:10:57
'''
    Original Copyright, Comments and Notices from source:

    COPYRIGHT Sourced from Google Fonts, Wed 28 May 2025
    COPYRIGHT https://fonts.google.com/specimen/PT+Sans+Narrow
    COPYRIGHT 
    COPYRIGHT Distributed there under the SIL Open Font License, Version 1.1
    COPYRIGHT 
    COPYRIGHT -----------------------------------------------------------
    COPYRIGHT Copyright (c) 2010, ParaType Ltd. (http://www.paratype.com/public),
    COPYRIGHT with Reserved Font Names "PT Sans" and "ParaType".
    COPYRIGHT 
    COPYRIGHT This Font Software is licensed under the SIL Open Font License, Version 1.1.
    COPYRIGHT This license is copied below, and is also available with a FAQ at:
    COPYRIGHT https://openfontlicense.org
    COPYRIGHT 
    COPYRIGHT 
    COPYRIGHT -----------------------------------------------------------
    COPYRIGHT SIL OPEN FONT LICENSE Version 1.1 - 26 February 2007
    COPYRIGHT -----------------------------------------------------------
    COPYRIGHT 
    COPYRIGHT PREAMBLE
    COPYRIGHT The goals of the Open Font License (OFL) are to stimulate worldwide
    COPYRIGHT development of collaborative font projects, to support the font creation
    COPYRIGHT efforts of academic and linguistic communities, and to provide a free and
    COPYRIGHT open framework in which fonts may be shared and improved in partnership
    COPYRIGHT with others.
    COPYRIGHT 
    COPYRIGHT The OFL allows the licensed fonts to be used, studied, modified and
    COPYRIGHT redistributed freely as long as they are not sold by themselves. The
    COPYRIGHT fonts, including any derivative works, can be bundled, embedded,
    COPYRIGHT redistributed and/or sold with any software provided that any reserved
    COPYRIGHT names are not used by derivative works. The fonts and derivatives,
    COPYRIGHT however, cannot be released under any other type of license. The
    COPYRIGHT requirement for fonts to remain under this license does not apply
    COPYRIGHT to any document created using the fonts or their derivatives.
    COPYRIGHT 
    COPYRIGHT DEFINITIONS
    COPYRIGHT "Font Software" refers to the set of files released by the Copyright
    COPYRIGHT Holder(s) under this license and clearly marked as such. This may
    COPYRIGHT include source files, build scripts and documentation.
    COPYRIGHT 
    COPYRIGHT "Reserved Font Name" refers to any names specified as such after the
    COPYRIGHT copyright statement(s).
    COPYRIGHT 
    COPYRIGHT "Original Version" refers to the collection of Font Software components as
    COPYRIGHT distributed by the Copyright Holder(s).
    COPYRIGHT 
    COPYRIGHT "Modified Version" refers to any derivative made by adding to, deleting,
    COPYRIGHT or substituting -- in part or in whole -- any of the components of the
    COPYRIGHT Original Version, by changing formats or by porting the Font Software to a
    COPYRIGHT new environment.
    COPYRIGHT 
    COPYRIGHT "Author" refers to any designer, engineer, programmer, technical
    COPYRIGHT writer or other person who contributed to the Font Software.
    COPYRIGHT 
    COPYRIGHT PERMISSION & CONDITIONS
    COPYRIGHT Permission is hereby granted, free of charge, to any person obtaining
    COPYRIGHT a copy of the Font Software, to use, study, copy, merge, embed, modify,
    COPYRIGHT redistribute, and sell modified and unmodified copies of the Font
    COPYRIGHT Software, subject to the following conditions:
    COPYRIGHT 
    COPYRIGHT 1) Neither the Font Software nor any of its individual components,
    COPYRIGHT in Original or Modified Versions, may be sold by itself.
    COPYRIGHT 
    COPYRIGHT 2) Original or Modified Versions of the Font Software may be bundled,
    COPYRIGHT redistributed and/or sold with any software, provided that each copy
    COPYRIGHT contains the above copyright notice and this license. These can be
    COPYRIGHT included either as stand-alone text files, human-readable headers or
    COPYRIGHT in the appropriate machine-readable metadata fields within text or
    COPYRIGHT binary files as long as those fields can be easily viewed by the user.
    COPYRIGHT 
    COPYRIGHT 3) No Modified Version of the Font Software may use the Reserved Font
    COPYRIGHT Name(s) unless explicit written permission is granted by the corresponding
    COPYRIGHT Copyright Holder. This restriction only applies to the primary font name as
    COPYRIGHT presented to the users.
    COPYRIGHT 
    COPYRIGHT 4) The name(s) of the Copyright Holder(s) or the Author(s) of the Font
    COPYRIGHT Software shall not be used to promote, endorse or advertise any
    COPYRIGHT Modified Version, except to acknowledge the contribution(s) of the
    COPYRIGHT Copyright Holder(s) and the Author(s) or with their explicit written
    COPYRIGHT permission.
    COPYRIGHT 
    COPYRIGHT 5) The Font Software, modified or unmodified, in part or in whole,
    COPYRIGHT must be distributed entirely under this license, and must not be
    COPYRIGHT distributed under any other license. The requirement for fonts to
    COPYRIGHT remain under this license does not apply to any document created
    COPYRIGHT using the Font Software.
    COPYRIGHT 
    COPYRIGHT TERMINATION
    COPYRIGHT This license becomes null and void if any of the above conditions are
    COPYRIGHT not met.
    COPYRIGHT 
    COPYRIGHT DISCLAIMER
    COPYRIGHT THE FONT SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
    COPYRIGHT EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF
    COPYRIGHT MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT
    COPYRIGHT OF COPYRIGHT, PATENT, TRADEMARK, OR OTHER RIGHT. IN NO EVENT SHALL THE
    COPYRIGHT COPYRIGHT HOLDER BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
    COPYRIGHT INCLUDING ANY GENERAL, SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL
    COPYRIGHT DAMAGES, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
    COPYRIGHT FROM, OUT OF THE USE OR INABILITY TO USE THE FONT SOFTWARE OR FROM
    COPYRIGHT OTHER DEALINGS IN THE FONT SOFTWARE.
    COPYRIGHT -----------------------------------------------------------
    COPYRIGHT 
    COPYRIGHT Converted from OpenType font "PTSansNarrow.ttf" by "otf2bdf 3.0".
    COPYRIGHT 

    COMMENT "Copyright © 2009 ParaType Ltd. All rights reserved."
'''
version = '0.33'
name = '-freetype-pt sans narrow-medium-r-normal--19-140-100-100-p-72-iso10646-1'
family = 'pt sans narrow'
weight = 'medium'
size = 19

def height():
    return 20

def baseline():
    return 16

def max_width():
    return 16

def hmap():
    return True

def reverse():
    return False

def monospaced():
    return False

def min_ch():
    return 32

def max_ch():
    return 95

_g = {
  32:b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04',
  33:b'\x00\x00          \x00\x00 0\x00\x00\x00\x00\x05',
  34:b'\x00\x00xPPP\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x05',
  35:b'\x00\x00\x00\x00\x00\x00\x00\x00\x12\x00\x12\x00\x16\x00\x7f\x00$\x00$\x00$\x00~\x00\xa8\x00h\x00H\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\t',
  36:b'\x08\x00\x08\x00>\x00*\x00h\x00h\x00h\x008\x00\x18\x00\x0c\x00\n\x00\n\x00\x0b\x00\n\x00N\x00|\x00\x08\x00\x08\x00\x00\x00\x00\x00\t',
  37:b'\x00\x00\x00\x008 l@D\xc0D\x80m\x009\x00\x02\x00\x06\x00\x04\xe0\t \t \x1101 !\xe0\x00\x00\x00\x00\x00\x00\x00\x00\x0c',
  38:b'\x00\x00\x00\x00\x0e\x00\t\x00\x19\x00\x0b\x00\n\x00\x0c\x00\x1c\x006\x00# !@!\xc0 \xc01`\x1e \x00\x00\x00\x00\x00\x00\x00\x00\x0c',
  39:b'\x00\x00`@@@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03',
  40:b'\x00\x00\x10\x10  ``@@@@@@``  \x10\x10\x04',
  41:b'\x00\x00@` 00\x10\x10\x10\x10\x10\x10\x10\x1000 `@\x04',
  42:b'\x00\x00P0x0P\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x06',
  43:b'\x00\x00\x00\x00\x00\x00\x18\x18\x18~\x18\x18\x18\x00\x00\x00\x00\x00\x00\x00\x08',
  44:b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00`` @\x00\x00\x04',
  45:b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00x\x00\x00\x00\x00\x00\x00\x00\x00\x00\x06',
  46:b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00``\x00\x00\x00\x00\x03',
  47:b'\x00\x00\x02\x02\x04\x04\x04\x08\x08\x08\x10\x10\x10   @@\xc0\x00\x07',
  48:b'\x00\x00\x00\x00\x1c\x00&\x00b\x00C\x00C\x00C\x00C\x00C\x00C\x00C\x00C\x00b\x00&\x00\x1c\x00\x00\x00\x00\x00\x00\x00\x00\x00\t',
  49:b'\x00\x00\x00\x00\x08\x00\x18\x008\x00H\x00\x08\x00\x08\x00\x08\x00\x08\x00\x08\x00\x08\x00\x08\x00\x08\x00\x08\x00>\x00\x00\x00\x00\x00\x00\x00\x00\x00\t',
  50:b'\x00\x00\x00\x00<\x00F\x00\x06\x00\x02\x00\x06\x00\x06\x00\x04\x00\x04\x00\x0c\x00\x08\x00\x18\x000\x00 \x00~\x00\x00\x00\x00\x00\x00\x00\x00\x00\t',
  51:b'\x00\x00\x00\x00~\x00\x06\x00\x0c\x00\x0c\x00\x18\x00\x18\x00\x1c\x00\x06\x00\x02\x00\x02\x00\x02\x00\x02\x00F\x00|\x00\x00\x00\x00\x00\x00\x00\x00\x00\t',
  52:b'\x00\x00\x00\x00\x04\x00\x04\x00\x0c\x00\x1c\x00\x14\x004\x00$\x00D\x00\xff\x00\x04\x00\x04\x00\x04\x00\x04\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\t',
  53:b'\x00\x00\x00\x00>\x00 \x00 \x00 \x00 \x00<\x00\x04\x00\x06\x00\x02\x00\x02\x00\x02\x00\x06\x00\x04\x00x\x00\x00\x00\x00\x00\x00\x00\x00\x00\t',
  54:b'\x00\x00\x00\x00\x04\x00\x1e\x00\x10\x000\x00 \x00`\x00|\x00b\x00C\x00C\x00C\x00b\x00"\x00\x1c\x00\x00\x00\x00\x00\x00\x00\x00\x00\t',
  55:b'\x00\x00\x00\x00\x7f\x00\x02\x00\x06\x00\x06\x00\x04\x00\x0c\x00\x0c\x00\x08\x00\x08\x00\x18\x00\x10\x00\x10\x000\x00 \x00\x00\x00\x00\x00\x00\x00\x00\x00\t',
  56:b'\x00\x00\x00\x00\x1c\x00&\x00b\x00b\x00b\x006\x00\x1c\x00<\x00&\x00b\x00B\x00b\x00&\x00<\x00\x00\x00\x00\x00\x00\x00\x00\x00\t',
  57:b'\x00\x00\x00\x00<\x00f\x00B\x00C\x00C\x00C\x00c\x00>\x00\x02\x00\x02\x00\x06\x00\x0c\x00\x18\x000\x00\x00\x00\x00\x00\x00\x00\x00\x00\t',
  58:b'\x00\x00\x00\x00\x00\x00 `\x00\x00\x00\x00\x00\x00 `\x00\x00\x00\x00\x04',
  59:b'\x00\x00\x00\x00\x00\x00 0\x00\x00\x00\x00\x00\x00 p `\x00\x00\x04',
  60:b'\x00\x00\x00\x00\x00\x02\x0e\x180@0\x18\x0e\x02\x00\x00\x00\x00\x00\x00\x08',
  61:b'\x00\x00\x00\x00\x00\x00\x00~\x00\x00\x00~\x00\x00\x00\x00\x00\x00\x00\x00\x08',
  62:b'\x00\x00\x00\x00\x00@p\x18\x0c\x02\x0c\x18p@\x00\x00\x00\x00\x00\x00\x08',
  63:b'\x00\x00xL\x04\x04\x04\x0c\x18\x1000\x00\x0000\x00\x00\x00\x00\x07',
  64:b'\x00\x00\x00\x00\x00\x00\x03\xe0\x0c\x18\x18\x0c\x11\xe4#&""f"d"dbdfdD$\xec30\x10\x00\x0c\x00\x07\xe0\x00\x00\x10',
  65:b'\x00\x00\x00\x00\x08\x00\x08\x00\x1c\x00\x14\x00\x14\x00\x14\x006\x00"\x00"\x00\x7f\x00C\x00A\x00A\x00\xc1\x80\x00\x00\x00\x00\x00\x00\x00\x00\t',
  66:b'\x00\x00\x00\x00~\x00b\x00c\x00c\x00c\x00f\x00|\x00c\x00c\x00a\x00a\x00c\x00b\x00|\x00\x00\x00\x00\x00\x00\x00\x00\x00\t',
  67:b'\x00\x00\x00\x00\x1f\x001\x00 \x00`\x00`\x00@\x00@\x00@\x00@\x00`\x00`\x00 \x001\x00\x1f\x00\x00\x00\x00\x00\x00\x00\x00\x00\t',
  68:b'\x00\x00\x00\x00|\x00c\x00a\x00a\x80a\x80`\x80`\x80`\x80`\x80a\x80a\x80a\x00c\x00|\x00\x00\x00\x00\x00\x00\x00\x00\x00\n',
  69:b'\x00\x00~`````~``````~\x00\x00\x00\x00\x08',
  70:b'\x00\x00~`````~```````\x00\x00\x00\x00\x08',
  71:b'\x00\x00\x00\x00\x0f\x001\x00 \x00`\x00`\x00@\x00@\x00G\x80A\x80a\x80a\x80!\x801\x80\x1f\x00\x00\x00\x00\x00\x00\x00\x00\x00\t',
  72:b'\x00\x00\x00\x00`\x80`\x80`\x80`\x80`\x80`\x80\x7f\x80`\x80`\x80`\x80`\x80`\x80`\x80`\x80\x00\x00\x00\x00\x00\x00\x00\x00\n',
  73:b'\x00\x00``````````````\x00\x00\x00\x00\x04',
  74:b'\x00\x00\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\x10\xe0\x00\x00\x00\x00\x05',
  75:b'\x00\x00\x00\x00c\x00c\x00f\x00d\x00l\x00h\x00p\x00x\x00l\x00l\x00f\x00b\x00c\x00a\x80\x00\x00\x00\x00\x00\x00\x00\x00\t',
  76:b'\x00\x00`````````````\x7f\x00\x00\x00\x00\x08',
  77:b'\x00\x00\x00\x00````P\xa0P\xa0p\xe0y`i`o`f`f`d```````\x00\x00\x00\x00\x00\x00\x00\x00\x0c',
  78:b'\x00\x00\x00\x00@\x80`\x80`\x80P\x80x\x80x\x80l\x80d\x80f\x80b\x80c\x80a\x80a\x80`\x80\x00\x00\x00\x00\x00\x00\x00\x00\n',
  79:b'\x00\x00\x00\x00\x1e\x001\x00!\x80`\x80@\x80@\xc0@\xc0@\xc0@\xc0`\x80`\x80!\x801\x00\x1e\x00\x00\x00\x00\x00\x00\x00\x00\x00\n',
  80:b'\x00\x00\x00\x00|\x00b\x00c\x00a\x00c\x00c\x00b\x00|\x00`\x00`\x00`\x00`\x00`\x00`\x00\x00\x00\x00\x00\x00\x00\x00\x00\t',
  81:b'\x00\x00\x00\x00\x1e\x001\x00!\x80`\x80@\x80@\xc0@\xc0@\xc0@\xc0`\x80`\x80!\x801\x00\x1e\x00\x00\x00\x1c\x00\x07\x00\x01\xe0\n',
  82:b'\x00\x00\x00\x00|\x00f\x00b\x00c\x00c\x00b\x00f\x00|\x00l\x00d\x00f\x00b\x00c\x00a\x80\x00\x00\x00\x00\x00\x00\x00\x00\t',
  83:b'\x00\x00>b@@`0\x18\x0c\x06\x02\x02\x02F|\x00\x00\x00\x00\x08',
  84:b'\x00\x00\x00\x00\xff\x00\x08\x00\x08\x00\x08\x00\x08\x00\x08\x00\x08\x00\x08\x00\x08\x00\x08\x00\x08\x00\x08\x00\x08\x00\x08\x00\x00\x00\x00\x00\x00\x00\x00\x00\t',
  85:b'\x00\x00\x00\x00a\x80a\x80a\x80a\x80a\x80a\x80a\x80a\x80a\x80a\x80a\x80a\x001\x00\x1e\x00\x00\x00\x00\x00\x00\x00\x00\x00\n',
  86:b'\x00\x00\x00\x00\xc1\x80\xc1\x00A\x00C\x00c\x00"\x00"\x006\x004\x00\x14\x00\x14\x00\x14\x00\x08\x00\x08\x00\x00\x00\x00\x00\x00\x00\x00\x00\t',
  87:b'\x00\x00\x00\x00\xc2\x18\xc2\x10F\x10E\x10e0e e -\xa0(\xa0(\xe08\xc0\x18\xc0\x10\xc0\x10@\x00\x00\x00\x00\x00\x00\x00\x00\r',
  88:b'\x00\x00\x00\x00a\x80a\x00#\x002\x00\x16\x00\x1c\x00\x0c\x00\x0c\x00\x14\x00\x16\x002\x00#\x00a\x00\xc1\x80\x00\x00\x00\x00\x00\x00\x00\x00\n',
  89:b'\x00\x00\x00\x00\xc1\x80C\x00c\x00"\x006\x004\x00\x14\x00\x18\x00\x08\x00\x08\x00\x08\x00\x08\x00\x08\x00\x08\x00\x00\x00\x00\x00\x00\x00\x00\x00\t',
  90:b'\x00\x00\x7f\x03\x02\x06\x04\x0c\x08\x18\x100 `@\x7f\x00\x00\x00\x00\x08',
  91:b'\x00\x00p````````````````p\x05',
  92:b'\x00\x00\xc0@`  0\x10\x10\x18\x08\x08\x0c\x04\x06\x02\x02\x00\x00\x07',
  93:b'\x00\x00p0000000000000000p\x05',
  94:b'\x00\x00\x10\x18,$F\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x08',
  95:b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xfc\x06',
}

def get_ch(ch):
    c = ord(ch)
    if c not in _g.keys():
        return None, 0, 0
    return memoryview(_g[c]), 20, int(_g[c][-1])
