'''
    ezFBfont_b12_n : generated as part of the microPyEZfonts repository
      https://github.com/easytarget/microPyEZfonts

    This font definition can be used with the "ezFBfont" class provided there.
    It can also be used with the "writer" class from Peter Hinches micropython
      font-to-py tool: https://github.com/peterhinch/micropython-font-to-py

    Original b12.bdf font file was sourced from the U8G2 project:
      https://github.com/olikraus/u8g2

    Original Copyright information from source:
    COPYRIGHT "(c) Copyright 2000-2003 /efont/ The Electronic Font Open Laboratory."

    Original Comments and Notices from source:
    (may include copyright and trademark info):
    None found
'''
# Code generated by bdf2dict.py
# Font: b12 Char set: b' %()*+,-./0123456789:\xb0'
# Cmd: ['bdf2dict.py', 'bdf-sources/b12.bdf', '../latin-1/n-char.set']
# Date: 2024-06-04 14:20:06

version = '0.33'
name = '-Efont-Biwidth-Medium-R-Normal--12-120-75-75-P-60-ISO10646-1'
family = 'Biwidth'
weight = 'Medium'
size = 12

def height():
    return 10

def baseline():
    return 9

def max_width():
    return 6

def hmap():
    return True

def reverse():
    return False

def monospaced():
    return True

def min_ch():
    return 32

def max_ch():
    return 176

_g = {
 32:[b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'],
 37:[b'\x00\x00dd\x08\x10 LL\x00'],
 40:[b'\x00\x08\x10\x10   \x10\x10\x08'],
 41:[b'\x00 \x10\x10\x08\x08\x08\x10\x10 '],
 42:[b'\x00\x00\x10T8\x108T\x10\x00'],
 43:[b'\x00\x00\x00\x10\x10|\x10\x10\x00\x00'],
 44:[b'\x00\x00\x00\x00\x00\x00\x0000`'],
 45:[b'\x00\x00\x00\x00\x00|\x00\x00\x00\x00'],
 46:[b'\x00\x00\x00\x00\x00\x00\x0000\x00'],
 47:[b'\x00\x00\x04\x08\x08\x10  @\x00'],
 48:[b'\x00\x00\x18$$$$$\x18\x00'],
 49:[b'\x00\x00\x100\x10\x10\x10\x108\x00'],
 50:[b'\x00\x008D\x04\x08\x10 |\x00'],
 51:[b'\x00\x00|\x04\x08\x18\x04D8\x00'],
 52:[b'\x00\x00\x08\x18(H|\x08\x08\x00'],
 53:[b'\x00\x00|@x\x04\x04D8\x00'],
 54:[b'\x00\x00\x18 @xDD8\x00'],
 55:[b'\x00\x00|\x04\x08\x08\x10\x10\x10\x00'],
 56:[b'\x00\x008DD8DD8\x00'],
 57:[b'\x00\x008DD<\x04\x080\x00'],
 58:[b'\x00\x00\x00\x0000\x0000\x00'],
 176:[b'\x18$$\x18\x00\x00\x00\x00\x00\x00'],
}

def get_ch(ch):
    c = ord(ch)
    if c not in _g.keys():
        return None, 0, 0
    return memoryview(_g[c][0]), height(), max_width()

