'''
    ezFBfont_10_7x14B_time : generated as part of the microPyEZfonts repository
      https://github.com/easytarget/microPyEZfonts

    This font definition can be used with the "ezFBfont" class provided there.
    It can also be used with the "writer" class from Peter Hinches micropython
      font-to-py tool: https://github.com/peterhinch/micropython-font-to-py

    Original 7x14B.bdf font file was sourced from the U8G2 project:
      https://github.com/olikraus/u8g2

    Original Copyright information from source:
    COPYRIGHT "Public domain font.  Share and enjoy."

    Original Comments and Notices from source:
    (may include copyright and trademark info):
    None found
'''
# Code generated by bdf2dict.py
# Font: 7x14B
# Cmd: [bdf2dict.py], ['Latin-1-bdf-sources/7x14B.bdf', './time-char.set', 'True']
# Date: 2024-06-11 17:33:06

version = '0.33'
name = '-Misc-Fixed-Bold-R-Normal--14-130-75-75-C-70-ISO10646-1'
family = 'fixed'
weight = 'bold'
size = 14

def height():
    return 10

def baseline():
    return 10

def max_width():
    return 7

def hmap():
    return True

def reverse():
    return False

def monospaced():
    return True

def min_ch():
    return 32

def max_ch():
    return 58

_g = {
 32:[b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'],
 43:[b'\x00\x00000\xfc000\x00'],
 45:[b'\x00\x00\x00\x00\x00\xfc\x00\x00\x00\x00'],
 46:[b'\x00\x00\x00\x00\x00\x00\x00\x0000'],
 48:[b'x\xcc\xcc\xcc\xcc\xcc\xcc\xcc\xccx'],
 49:[b'0p\xf0000000\xfc'],
 50:[b'x\xcc\xcc\x0c\x18\x180`\xc0\xfc'],
 51:[b'x\xcc\xcc\x0c8\x0c\x0c\xcc\xccx'],
 52:[b'\x08\x18\x188x\xd8\xd8\xfc\x18\x18'],
 53:[b'\xfc\xc0\xc0\xf8\xcc\x0c\x0c\xcc\xccx'],
 54:[b'8l\xcc\xc0\xf8\xcc\xcc\xcc\xccx'],
 55:[b'\xfc\xcc\xd8\x18000000'],
 56:[b'x\xcc\xcc\xccxx\xcc\xcc\xccx'],
 57:[b'x\xcc\xcc\xcc\xcc|\x0c\xcc\xd8p'],
 58:[b'\x00\x0000\x00\x00\x0000\x00'],
}

def get_ch(ch):
    c = ord(ch)
    if c not in _g.keys():
        return None, 0, 0
    return memoryview(_g[c][0]), 10, 7

